### ISSUE TITLE
application crashed after installing and attempting to use @fxts/core

### ISSUE THREAD

**Issue by st-clair-clarke** [marpple/FxTS#214]
# Bug Report

### 💻 Code

installed @fxts/core version 0.16.0

```ts

```

### 🙁 Actual behavior
application could not run

main.ts:24 Error: Unsatisfied version 0 from project1 of shared singleton module @fxts/core (required ~0.16.0)
    at getStrictSingletonVersion (main.js:456:58)
    at main.js:540:19
    at main.js:492:19
    at 93272 (main.js:578:26)
    at main.js:893:55
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (main.js:876:35)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
(anonymous) @ main.ts:24
invoke @ zone.js:368
run @ zone.js:129
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
runTask @ zone.js:173
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1100
(anonymous) @ zone.js:1116
webpackJsonpCallback @ main.js:981
(anonymous) @ apps_medsoft_src_bootstrap_ts.js:1
Show 15 more frames

### 🙂 Expected behavior
Application to run as usual

---

### Version Information

- Operating system: Linux
- Typescript: "typescript": "~5.0.4"
- Nodejs: "typescript": "~5.0.4"

**Comment by ppeeou** [comment]
@st-clair-clarke 
Thanks for reporting the issue.

However, looking at the error message, it is difficult to infer what environment caused the error stack to occur.

Could you provide an environment(repo) to reproduce the issue?

**Comment by hg-pyun** [comment]
This issue is being closed as it is no longer under active tracking.
