### ISSUE TITLE
Unsatisfied version 0 from registration of shared singleton module @fxts/core (required ~0.18.0)

### ISSUE THREAD

**Issue by st-clair-clarke** [marpple/FxTS#222]
# Bug Report

Attempting to execute code in which @fxts/core is used results in error

```
Uncaught (in promise): Error: Unsatisfied version 0 from registration of shared singleton module @fxts/core (required ~0.18.0)
Error: Unsatisfied version 0 from registration of shared singleton module @fxts/core (required ~0.18.0)
    at getStrictSingletonVersion (consumes:49:1)
    at consumes:133:1
    at consumes:85:1
    at 75394 (consumes:162:1)
    at consumes:460:1
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (consumes:443:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25998:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25998:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:26308:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)
```

### 💻 Code

```ts
import { isBoolean } from '@fxts/core'

export function matchBoolean(ctrl: AbstractControl): IValidationResult | null {
   return isBoolean(ctrl.value)
      ? null
      : { matchBoolean: { message: message('required') } }
}

```

### 🙁 Actual behavior

The library fails to open

### 🙂 Expected behavior

The library should open - this actually occurs after removal of all codes involving @fxts/core

---

### Version Information

- Operating system: MX Linux 23
- Typescript: "typescript": "~5.1.6"
- Nodejs: v20.5.0

**Comment by shine1594** [comment]
Could you write a minimal amount of code that can reproduce that error? It would be great if you could write it similar to this repository: https://github.com/shine1594/fxts-test

**Comment by st-clair-clarke** [comment]
Is someone trying to solve this bug? I am still getting it with the current release of @fxts/core libs? I am using pnpm and it is the only package that I have ever seen this issue.

**Comment by ppeeou** [comment]
@st-clair-clarke 

Could you provide an environment where I can check the issue?
fxts recommends tsconfig `strict:true`.
